<?php
$image1 = 'gambar/all-desain.jpg'; 
$image2 = 'gambar/qr1.png';
$image3 = 'gambar/qr2.png';
$image4 = 'gambar/qr3.png';
$image5 = 'gambar/qr4.png';
$image6 = 'gambar/qr5.png';
$image7 = 'gambar/qr1.png';
$image8 = 'gambar/qr2.png';
$image9 = 'gambar/qr3.png';
$image10 = 'gambar/qr4.png';
$image11 = 'gambar/qr5.png';
$image12 = 'gambar/qr1.png';
$image13 = 'gambar/qr2.png';
$image14 = 'gambar/qr3.png';
$image15 = 'gambar/qr4.png';
$image16 = 'gambar/qr5.png';
$width_size =50;
$height_size = 50;
list($width_size, $height_size) = getimagesize($image2);
list($width_size, $height_size) = getimagesize($image3);
list($width_size, $height_size) = getimagesize($image4);
list($width_size, $height_size) = getimagesize($image5);
list($width_size, $height_size) = getimagesize($image6);
list($width_size, $height_size) = getimagesize($image7);
list($width_size, $height_size) = getimagesize($image8);
list($width_size, $height_size) = getimagesize($image9);
list($width_size, $height_size) = getimagesize($image10);
list($width_size, $height_size) = getimagesize($image11);
list($width_size, $height_size) = getimagesize($image12);
list($width_size, $height_size) = getimagesize($image13);
list($width_size, $height_size) = getimagesize($image14);
list($width_size, $height_size) = getimagesize($image15);
list($width_size, $height_size) = getimagesize($image16);
$image1 = imagecreatefromstring(file_get_contents($image1));
$image2 = imagecreatefromstring(file_get_contents($image2));
$image3 = imagecreatefromstring(file_get_contents($image3));
$image4 = imagecreatefromstring(file_get_contents($image4));
$image5 = imagecreatefromstring(file_get_contents($image5));
$image6 = imagecreatefromstring(file_get_contents($image6));
$image7 = imagecreatefromstring(file_get_contents($image7));
$image8 = imagecreatefromstring(file_get_contents($image8));
$image9 = imagecreatefromstring(file_get_contents($image9));
$image10 = imagecreatefromstring(file_get_contents($image10));
$image11 = imagecreatefromstring(file_get_contents($image11));
$image12 = imagecreatefromstring(file_get_contents($image12));
$image13 = imagecreatefromstring(file_get_contents($image13));
$image14 = imagecreatefromstring(file_get_contents($image14));
$image15 = imagecreatefromstring(file_get_contents($image15));
$image16 = imagecreatefromstring(file_get_contents($image16));
imagecopymerge($image1, $image2, 150, 370, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image3, 770, 370, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image4, 1400, 370, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image5, 2015, 370, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image6, 2635, 370, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image7, 150, 1275, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image8, 770, 1275, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image9, 1380, 1275, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image10, 2000, 1275, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image11, 2620, 1275, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image12, 145, 2170, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image13, 760, 2170, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image14, 1380, 2170, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image15, 2000, 2170, 0, 0, $width_size, $height_size, 100);
imagecopymerge($image1, $image16, 2620, 2170, 0, 0, $width_size, $height_size, 100);
header('Content-Type: image/png');
imagepng($image1);
imagepng($image1, 'contoh.tif');
?>